const data = {
  users: [
    {
      fullname: "Kabore Abdul Mahamoudou",
      username: "iamMAHAM",
      email: "abdulkabore@gmail.com",
      password: "$2b$10$RkZG1s9bz62ol5VcKkxA5.E7w99XtXuWl47MxDr92/fLFQleJL1p2",
      birthday: new Date("1999-11-23T00:00:00.000+00:00"),
      avatar: "https://i.imgur.com/9pNffkj.png",
      emailVerified: true,
      role: ["admin", "principal", "owner", "user"],
    },
    {
      fullname: "Kouame Koffi Rameaux",
      username: "ramseycoder",
      email: "kouamekoffi080@gmail.com",
      password: "azerty123@TT.@",
      birthday: new Date("2000-12-02T12:18:55.547Z").toISOString(),
      avatar: "https://imgur.com/t/profile_picture/Fb35ibq",
      emailVerified: true,
      role: ["user", "moderator"],
    },
    {
      fullname: "Fabien brou",
      username: "fabien",
      email: "fabien@gmail.com",
      password: "azerty123@TT.@",
      birthday: new Date("2000-12-02T12:18:55.547Z").toISOString(),
      avatar: "https://imgur.com/t/profile_picture/Fb35ibq",
      emailVerified: true,
      role: ["user", "blogger"],
    },
  ],
  products: [
    {
      name: "Free Shirt 1",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInsStock: 20,
      description: "A popular shirt",
    },
    {
      name: "slim Shirt 2",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4,
      numReviews: 56,
      countInsStock: 1,
      description: "A popular shirt",
    },
    {
      name: "golf shirt 3",
      slug: "golf-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 105,
      brand: "Maham",
      rating: 5,
      numReviews: 6,
      countInsStock: 250,
      description: "A popular shirt",
    },
    {
      name: "free pants 1",
      slug: "free-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 105,
      brand: "Maham",
      rating: 5,
      numReviews: 6,
      countInsStock: 250,
      description: "A popular shirt",
    },
    {
      name: "slim pants 2",
      slug: "slim-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 105,
      brand: "Maham",
      rating: 5,
      numReviews: 6,
      countInsStock: 250,
      description: "A popular shirt",
    },
    {
      name: "golf pants  3",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 105,
      brand: "Maham",
      rating: 5,
      numReviews: 6,
      countInsStock: 250,
      description: "A popular shirt",
    },
  ],
};

export default data;
