const data = {
  products: [
    {
      name: 'Free Shirt 1',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInsStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'slim Shirt 2',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4,
      numReviews: 56,
      countInsStock: 1,
      description: 'A popular shirt',
    },
    {
      name: 'golf shirt 3',
      slug: 'golf-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 105,
      brand: 'Maham',
      rating: 5,
      numReviews: 6,
      countInsStock: 250,
      description: 'A popular shirt',
    },
    {
      name: 'free pants 1',
      slug: 'free-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 105,
      brand: 'Maham',
      rating: 5,
      numReviews: 6,
      countInsStock: 250,
      description: 'A popular shirt',
    },
    {
      name: 'slim pants 2',
      slug: 'slim-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 105,
      brand: 'Maham',
      rating: 5,
      numReviews: 6,
      countInsStock: 250,
      description: 'A popular shirt',
    },
    {
      name: 'golf pants  3',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 105,
      brand: 'Maham',
      rating: 5,
      numReviews: 6,
      countInsStock: 250,
      description: 'A popular shirt',
    },
  ],
};

export default data;
